### ISSUE TITLE
iterm2 vim 8.1 color weird

### ISSUE THREAD

**Issue by docoder** [kaicataldo/material.vim#40] opened 2020-03-10 00:53 UTC
![1583801589899](https://user-images.githubusercontent.com/8859778/76269436-9ca24a80-62ac-11ea-8598-a7ad56ffd901.jpg)

**Comment by docoder** [comment] 2020-03-10 00:54
iterm2 3.3.9

**Comment by kaicataldo** [comment] 2020-03-10 20:08
I am unable to reproduce this with the same versions of iTerm2 and Vim. Some follow-up questions:

1. Are you using tmux?
2. Have you tried finding the minimal repro case by removing other things in your Vim config?

**Comment by reidcooper** [comment] 2020-03-17 18:35
I am encountering this issue.

Deleted all plugins and re-installed them.

```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Dec 13 2019 14:45:40)
Included patches: 1-503, 505-680, 682-1312
```
No tmux - same results though.
iTerm 2 Build 3.3.9

<img width="1678" alt="Screenshot 2020-03-17 14 35 28" src="https://user-images.githubusercontent.com/6921277/76889759-8ec86880-685c-11ea-960a-2e854284964a.png">

**Comment by kaicataldo** [comment] 2020-03-17 18:51
Since I'm unable to reproduce, would appreciate if someone could figure out repro steps.

**Comment by reidcooper** [comment] 2020-03-18 21:55
I reinstalled iTerm and Vim. Didn't fix it. 

But I nuked my `~/.vim` directory and started over which solved the problem for me.

I had a feeling it was something to do with `vim-plug` but I have no idea.

Thanks. My issue has been solved.

**Comment by gko** [comment] 2020-03-19 10:56
@reidcooper can you make a repo with working config?

**Comment by gko** [comment] 2020-03-19 11:14
here is my example config:
https://github.com/gko/vimrc-material-example

works perfectly with neovim

but for some reason not with vim (`iterm` or `terminal`)

tried both importing colors into iterm and without importing them.

**Comment by docoder** [comment] 2020-03-20 08:11
`.zshrc` add 
`alias vim='/Applications/MacVim.app/Contents/MacOS/Vim'` 
fixed it

**Comment by docoder** [comment] 2020-03-20 08:13
vim version 8.2.319

**Comment by gko** [comment] 2020-03-20 21:32
`vim` in macOS doesn't support `termguicolors`.

So there are three options:
1. update vim to 8.2 and get the support in `iTerm 2`
2. add `cterm` support in color theme (added draft #41)
3. check for `termguicolors` support and set a fallback theme like here:
https://github.com/gko/vimio/blob/master/.vimrc_background#L17-L27

**Comment by kaicataldo** [comment] 2020-03-21 03:30
Please see the readme. Information about [true colors](https://github.com/kaicataldo/material.vim#true-colors) can be found here.

**Comment by gko** [comment] 2020-03-22 17:48
@kaicataldo I know, I just summed it up for the people that will come across this issue

**Comment by kaicataldo** [comment] 2020-03-22 18:45
Thanks, appreciated :)

**Comment by kaicataldo** [comment] 2020-04-01 16:41
Closing since this has been resolved.

**Closed as completed by kaicataldo** 2020-04-01 16:41 UTC
Labels: can't reproduce
