### ISSUE TITLE
Conceal characters colors not set

### ISSUE THREAD

**Issue by RicherMans** [kaicataldo/material.vim#12] opened 2019-03-01 03:39 UTC
Hey there, 
I love that theme but had for quite some time a problem with it, that it renders conceal characters with wrong colors( by default DarkGrey ):

![screenshot_20190301_105206](https://user-images.githubusercontent.com/3957278/53614909-8338de00-3c16-11e9-86b8-cc90f09868d0.png)

I checked the documentation for neovim and vim and found the reason:

```bash
hi Conceal guibg=material guifg=material
```
Fixes it, but doesn't look super good. If you have time, could you tell me which colors should be appropriate ?

**Comment by kaicataldo** [comment] 2019-03-06 04:17
Hey, I'm currently on vacation, but happy to take a look when I get back.

__Edit:__ I'd like to actually take the time to do this right, but if you wanted a quick fix in the interim you should be able to add the following line in [this file](https://github.com/kaicataldo/material.vim/blob/master/colors/material.vim#L118) for a quick fix:
```
call s:HL('Conceal', s:gray4, '', '')
```

If you don't like the color defined by `s:gray4`, you can use any of [the other defined colors](https://github.com/kaicataldo/material.vim/blob/master/colors/material.vim#L20-L39) or provide your own hex color code.

I'll take a look when I'm back from my vacation and can do a proper fix :)

**Comment by kaicataldo** [comment] 2019-06-28 19:59
I've just done a major rewrite of the full theme. Is this still an issue?

**Comment by RicherMans** [comment] 2019-06-30 06:17
Hey there,
unfortunately yes, still the same as before, but the theme looks much better now!

![Screenshot_20190630_141617](https://user-images.githubusercontent.com/3957278/60393054-c746db80-9b41-11e9-993d-bfa714a06c6b.png)

**Comment by kaicataldo** [comment] 2019-06-30 14:13
Thanks for the kind words. I’ll try to get a patch in to fix this today.

**Comment by kaicataldo** [comment] 2019-06-30 15:52
@RicherMans Can you give me reproduction steps? I'm realizing that I don't use `Conceal` characters in any of the work I do (which is why these colors aren't set!).

**Comment by RicherMans** [comment] 2019-06-30 16:06
Hey sure, as far as I am concerned, just need in your `~/.config/nvim/init.vim`  to add:

```
Plug 'vim-pandoc/vim-pandoc-syntax'

setlocal conceallevel=2
let g:pandoc#syntax#conceal#use = 1
```

and then just open any .md file. 

Moreover, I cursorcolumn and cursorrow seem a bit weird with that black color:

![Screenshot_20190701_000553](https://user-images.githubusercontent.com/3957278/60399226-0140cd80-9b94-11e9-8f49-9e9ae646e425.png)

**Comment by kaicataldo** [comment] 2019-06-30 16:23
Great, thanks - I'll see if I can fix that up.

The `CursorLine` color is intended - it matches the original theme. I set `CursorColumn` to match, which I _think_ makes sense. I don't `set cursorcolumn` myself, so this is my first time actually seeing it. How do other themes typically handle this?

**Comment by kaicataldo** [comment] 2019-06-30 17:10
This should now be fixed by https://github.com/kaicataldo/material.vim/commit/b23a99b9b1aeae4f717ab9d6b4a6a5b33de522b4.

I also update the fold colors so that they wouldn't conflict with the relative number color.

Please confirm if you get a chance!

**Comment by RicherMans** [comment] 2019-07-01 00:29
They there, 
yeah is somewhat fixed, before all conceal characters had a different background color than the theme, but now they are nearly invisible e.g.,:

![Screenshot_20190701_082531](https://user-images.githubusercontent.com/3957278/60404301-1f312100-9bda-11e9-8dae-6017d3e5e3b6.png)

Compare with e.g., one theme:

![Screenshot_20190701_082737](https://user-images.githubusercontent.com/3957278/60404297-18a2a980-9bda-11e9-9fe1-29e4215de073.png)

Also since the revamp, the error bar to the left is weirdly colored and symbols rather invisible:

![Screenshot_20190701_082323](https://user-images.githubusercontent.com/3957278/60404313-51db1980-9bda-11e9-801d-77c1481d06b9.png)

**Comment by kaicataldo** [comment] 2019-07-01 02:24
We can definitely add a background color to Conceal characters if that's what others themes tend to do. As far the line numbers go, I changed it to match the VS Code themes.

Edit: I intentionally made the Conceal characters unobtrusive, since they're not actual syntax. Maybe that was a bad assumption - again, I don't really use them.

**Comment by kaicataldo** [comment] 2019-07-01 18:24
I'm going to go ahead and close this issue because the bug is fixed (`Conceal` not being set). Totally open to having discussions around changing colors, but I think it would be helpful to do that on a new issue (or on this [PR](https://github.com/kaicataldo/material.vim/pull/24)). I'm still fixing a few regressions from the rewrite, and I think it's useful to distinguish regressions for enhancements!

**Closed as completed by kaicataldo** 2019-07-01 18:24 UTC
Labels: bug
